// Code generated by "stringer -type=Encoding"; DO NOT EDIT.

package sallust

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[EncodingJSON-0]
	_ = x[EncodingConsole-1]
}

const _Encoding_name = "EncodingJSONEncodingConsole"

var _Encoding_index = [...]uint8{0, 12, 27}

func (i Encoding) String() string {
	if i < 0 || i >= Encoding(len(_Encoding_index)-1) {
		return "Encoding(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Encoding_name[_Encoding_index[i]:_Encoding_index[i+1]]
}
